### ISSUE TITLE
Add `pre-commit` hooks

### ISSUE THREAD

**Issue by jrdnbradford** [jrdnbradford/readMDTable#9]
Perhaps something like:
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: no-commit-to-branch
  - id: end-of-file-fixer

- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.3
  hooks:
  - id: parsable-R
  - id: use-tidy-description
  - id: roxygenize
  - id: no-print-statement
  - id: readme-rmd-rendered
  - id: deps-in-desc 
```
